python -m unittest discover -s ..\tests -v -p test_1messageHandler.py
python -m unittest discover -s ..\tests -v -p test_calcTB.py
python -m unittest discover -s ..\tests -v -p test_eng1.py
python -m unittest discover -s ..\tests -v -p test_eng2.py
python -m unittest discover -s ..\tests -v -p test_eng3.py
python -m unittest discover -s ..\tests -v -p test_icartt.py
python -m unittest discover -s ..\tests -v -p test_iwg.py
python -m unittest discover -s ..\tests -v -p test_MTPclient.py
python -m unittest discover -s ..\tests -v -p test_MTPprocessor.py
python -m unittest discover -s ..\tests -v -p test_MTPviewer.py
python -m unittest discover -s ..\tests -v -p test_MTPviewer2.py
python -m unittest discover -s ..\tests -v -p test_quit.py
python -m unittest discover -s ..\tests -v -p test_rcf_set.py
python -m unittest discover -s ..\tests -v -p test_rcf.py
python -m unittest discover -s ..\tests -v -p test_readascii_parms.py
python -m unittest discover -s ..\tests -v -p test_readGVnc.py
python -m unittest discover -s ..\tests -v -p test_readmtp.py
python -m unittest discover -s ..\tests -v -p test_retriever.py
python -m unittest discover -s ..\tests -v -p test_tempresist.py
python -m unittest discover -s ..\tests -v -p test_tropopause.py
python -m unittest discover -s ..\tests -v -p test_udp.py