###############################################################################
# Code to display a GUI front-end to MTPcontrol
#
# Written in Python 3
#
# COPYRIGHT:   University Corporation for Atmospheric Research, 2022
###############################################################################
from PyQt5.QtWidgets import QWidget, QPushButton, QPlainTextEdit, \
                            QVBoxLayout, QLabel, QHBoxLayout, QGroupBox
from PyQt5 import QtGui
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import (QLineEdit, QDialog)
from EOLpython.Qlogger.messageHandler import QLogger as logger


class MTPControlView(QWidget):

    def __init__(self, app, client):

        self.app = app
        self.client = client

        # The QMainWindow class provides a main application window
        super().__init__()

        # Create the GUI
        self.initUI()
        self.show()

        # Process any events generated by the GUI so it stays responsive to the
        # user.
        self.app.processEvents()

    def initUI(self):
        """ Create the GUI """

        # Lables
        self.probeStatus = QLabel("Probe Status")
        self.scanStatus = QLabel("Scan Status ")  # space is so layout is even
        self.receivingIWG = QLabel("IWG Packet Status")
        self.IWGPort = QLabel("IWG Port #")
        self.sendingUDP = QLabel("UDP Status")
        self.UDPPort = QLabel("UDP out Port #")
        self.overHeat = QLabel("Overheat    ")  # space is so layout is even
        self.overVoltage = QLabel("Overvoltage ")  # space is so layout is even
        self.projectName = QLabel("Project Name")
        self.flightNumber = QLabel("Flight #")
        self.planeName = QLabel("Aircraft Name")
        self.nominalPitch = QLabel("Nominal Pitch")
        self.frequencies = QLabel("Frequencies")
        self.allScanAngles = QLabel("Elevation Angles:")
        self.projectLocation = QLabel("Data/logs saved to:")

        self.loopTimer = QLabel("Time since last scan")
        self.totalNumFrames = QLabel("Total scans")
        self.numFramesSinceLastReset = QLabel("Scans since reset")
        self.elAngle = QLabel("Current El. Angle")
        self.IWG1 = QLabel("IWG1")

        # Text boxes
        self.shortWidth = 60  # Width of small text boxes

        self.projectLocationBox = QLineEdit()
        self.projectLocationBox.setStyleSheet("padding-left:5")
        self.projectLocationBox.setText('~/Desktop/$Project')  # JAA
        self.projectLocationBox.setReadOnly(True)

        self.loopTimerBox = QLineEdit()
        self.loopTimerBox.setText('Start')
        self.loopTimerBox.setStyleSheet("padding-left:5")
        self.loopTimerBox.setFixedWidth(self.shortWidth)
        self.loopTimerBox.setReadOnly(True)
        self.totalNumFramesBox = QLineEdit()
        self.totalNumFramesBox.setText('0')
        self.totalNumFramesBox.setStyleSheet("padding-left:5")
        self.totalNumFramesBox.setFixedWidth(self.shortWidth)
        self.totalNumFramesBox.setReadOnly(True)
        self.numFramesSinceLastResetBox = QLineEdit()
        self.numFramesSinceLastResetBox.setText('0')
        self.numFramesSinceLastResetBox.setStyleSheet("padding-left:5")
        self.numFramesSinceLastResetBox.setFixedWidth(self.shortWidth)
        # self.numFramesSinceLastResetBox.setOverwriteMode(True)
        self.numFramesSinceLastResetBox.setReadOnly(True)

        # from config.mtph
        self.planeNameBox = QLineEdit()
        self.planeNameBox.setText('NGV')
        self.planeNameBox.setStyleSheet("padding-left:5")
        self.planeNameBox.setReadOnly(True)
        self.nominalPitchBox = QLineEdit()
        self.nominalPitchBox.setText('3')
        self.nominalPitchBox.setStyleSheet("padding-left:5")
        self.nominalPitchBox.setFixedWidth(self.shortWidth)
        self.nominalPitchBox.setReadOnly(True)
        self.frequenciesBox = QLineEdit()  # also known as channels
        self.frequenciesBox.setText('55.51, 56.65, 58.8')
        self.frequenciesBox.setStyleSheet("padding-left:5;")
        self.frequenciesBox.setReadOnly(True)
        self.allScanAnglesBox = QPlainTextEdit()
        self.allScanAnglesBox.setPlainText(
            "80.00, 55.00, 42.00, 25.00, 12.00, 0.00, -12.00, -25.00, " +
            "-42.00, -80.00")
        self.allScanAnglesBox.setFixedHeight(40)
        self.allScanAnglesBox.setReadOnly(True)
        # Current elevation - GUI updates before correction applied
        self.elAngleBox = QLineEdit()
        self.elAngleBox.setText('Target')
        self.elAngleBox.setStyleSheet("padding-left:5")
        self.elAngleBox.setFixedWidth(self.shortWidth)
        # self.elAngleBox.setOverwriteMode(True)
        self.elAngleBox.setReadOnly(True)

        # from/to (flight name) config.yaml
        self.projectNameBox = QLineEdit()
        self.projectNameBox.setText('ProjectName')
        self.projectNameBox.setStyleSheet("padding-left:5")
        self.projectNameBox.setReadOnly(True)

        self.flightNumberBox = QLineEdit()
        self.flightNumberBox.setText('FlightNum')
        self.flightNumberBox.setStyleSheet("padding-left:5")
        self.flightNumberBox.setReadOnly(True)

        self.IWGPortBox = QLineEdit()
        self.IWGPortBox.setText('7071')
        self.IWGPortBox.setStyleSheet("padding-left:5")
        self.IWGPortBox.setFixedWidth(self.shortWidth)
        self.IWGPortBox.setReadOnly(True)
        self.UDPPortBox = QLineEdit()
        self.UDPPortBox.setText('32106')
        self.UDPPortBox.setStyleSheet("padding-left:5")
        self.UDPPortBox.setFixedWidth(self.shortWidth)
        self.UDPPortBox.setReadOnly(True)

        self.IWG1Box = QPlainTextEdit()
        self.IWG1Box.setPlainText('')
        self.IWG1Box.setReadOnly(True)

        # Push Buttons
        self.reInitProbe = QPushButton("(Re)init Probe")
        self.reInitProbe.clicked.connect(self.reInitProbeClicked)
        self.reInitProbe.setEnabled(False)  # Leave disabled for now
        self.scanStatusButton = QPushButton("Start Scanning")
        self.scanStatusButton.clicked.connect(self.scanStatusClicked)
        self.scanStatusButton.setEnabled(True)
        self.shutdownProbe = QPushButton("Quit")
        self.shutdownProbe.clicked.connect(self.shutdownProbeClicked)

        # staus 'LED's'
        self.probeStatusLED = QLabel('')
        self.setLEDred(self.probeStatusLED)
        self.scanStatusLED = QLabel('')
        self.setLEDred(self.scanStatusLED)
        self.receivingIWGLED = QLabel('')
        self.setLEDred(self.receivingIWGLED)
        self.sendingUDPLED = QLabel('')
        self.setLEDred(self.sendingUDPLED)
        self.overHeatLED = QLabel('')  # Updated at end of each scan
        self.setLEDgreen(self.overHeatLED)
        self.overVoltageLED = QLabel('')  # Updated at end of each scan
        self.setLEDgreen(self.overVoltageLED)

        # Control Buttons
        LineProbeStatus = QHBoxLayout()
        LineProbeStatus.addWidget(self.planeName)
        LineProbeStatus.addWidget(self.planeNameBox)
        LineProbeStatus.addStretch()
        LineProbeStatus.addWidget(self.reInitProbe)
        LineProbeStatus.addStretch()
        LineProbeStatus.addWidget(self.scanStatusButton)

        # Probe Status Indicators
        ProbeStatus = QVBoxLayout()
        ProbeStatus.addWidget(self.probeStatus)
        ProbeStatus.addWidget(self.probeStatusLED)
        ScanStatus = QVBoxLayout()
        ScanStatus.addWidget(self.scanStatus)
        ScanStatus.addWidget(self.scanStatusLED)
        overHeatStatus = QVBoxLayout()
        overHeatStatus.addWidget(self.overHeat)
        overHeatStatus.addWidget(self.overHeatLED)
        overVoltageStatus = QVBoxLayout()
        overVoltageStatus.addWidget(self.overVoltage)
        overVoltageStatus.addWidget(self.overVoltageLED)

        ProbeBox = QGroupBox()
        ProbeBox.setLayout(ProbeStatus)
        ScanBox = QGroupBox()
        ScanBox.setLayout(ScanStatus)
        overHeatBox = QGroupBox()
        overHeatBox.setLayout(overHeatStatus)
        overVoltageBox = QGroupBox()
        overVoltageBox.setLayout(overVoltageStatus)

        LineScanStatus = QHBoxLayout()
        LineScanStatus.setSpacing(0)  # Tighten up grey boxes
        LineScanStatus.setContentsMargins(2, 2, 2, 2)
        LineScanStatus.addWidget(ProbeBox)
        LineScanStatus.addStretch()
        LineScanStatus.addWidget(ScanBox)
        LineScanStatus.addStretch()
        LineScanStatus.addWidget(overHeatBox)
        LineScanStatus.addStretch()
        LineScanStatus.addWidget(overVoltageBox)

        # Scan timer
        LineTimer = QHBoxLayout()
        LineTimer.addWidget(self.loopTimerBox)
        LineTimer.addWidget(self.loopTimer)
        LineTimer.addStretch()
        LineTimer.addWidget(self.nominalPitch)
        LineTimer.addWidget(self.nominalPitchBox)

        # Total scans received and scan frequencies
        LineNumFrames = QHBoxLayout()
        LineNumFrames.addWidget(self.totalNumFramesBox)
        LineNumFrames.addWidget(self.totalNumFrames)
        LineNumFrames.addStretch()
        LineNumFrames.addWidget(self.frequencies)
        LineNumFrames.addWidget(self.frequenciesBox)

        # Total scans since last reset
        LineResetFrames = QHBoxLayout()
        LineResetFrames.addWidget(self.numFramesSinceLastResetBox)
        LineResetFrames.addWidget(self.numFramesSinceLastReset)

        # Elevation angles
        LineElAngle = QHBoxLayout()
        LineElAngle.addWidget(self.allScanAngles)
        LineElAngle.addStretch()
        LineElAngle.addWidget(self.elAngle)
        LineElAngle.addWidget(self.elAngleBox)

        LineAllAngle = QHBoxLayout()
        LineAllAngle.addWidget(self.allScanAnglesBox)

        # IWG receive info
        LineReceivingUDP = QHBoxLayout()
        LineReceivingUDP.addWidget(self.receivingIWGLED)
        LineReceivingUDP.addWidget(self.receivingIWG)
        LineReceivingUDP.addStretch()
        LineReceivingUDP.addWidget(self.IWGPort)
        LineReceivingUDP.addWidget(self.IWGPortBox)

        # UDP data packet send info
        LineSendingUDP = QHBoxLayout()
        LineSendingUDP.addWidget(self.sendingUDPLED)
        LineSendingUDP.addWidget(self.sendingUDP)
        LineSendingUDP.addStretch()
        LineSendingUDP.addWidget(self.UDPPort)
        LineSendingUDP.addWidget(self.UDPPortBox)

        # Project name and flight number
        LineProjectName = QHBoxLayout()
        LineProjectName.addWidget(self.projectName)
        LineProjectName.addWidget(self.projectNameBox)
        LineProjectName.addStretch()
        LineProjectName.addWidget(self.flightNumber)
        LineProjectName.addWidget(self.flightNumberBox)

        # Put it all together
        mainbox = QVBoxLayout()
        mainbox.addLayout(LineProjectName)
        mainbox.addLayout(LineProbeStatus)
        mainbox.addLayout(LineScanStatus)
        mainbox.addLayout(LineTimer)
        mainbox.addLayout(LineNumFrames)
        mainbox.addLayout(LineResetFrames)
        mainbox.addLayout(LineElAngle)
        mainbox.addLayout(LineAllAngle)
        mainbox.addLayout(LineReceivingUDP)
        mainbox.addLayout(LineSendingUDP)
        mainbox.addWidget(self.projectLocation)
        mainbox.addWidget(self.projectLocationBox)
        mainbox.addWidget(self.IWG1)
        mainbox.addWidget(self.IWG1Box)
        mainbox.addWidget(self.shutdownProbe)

        self.setLayout(mainbox)

        # Set the initial size of the window created and where it will appear
        # on the screen (x locn, y locn, width, ht). It is user resizeable
        self.setGeometry(50, 50, 400, 500)

        # Set window title
        self.setWindowTitle('MTPControl')

    def reInitProbeClicked(self):
        """ Reinitialize probe. Used if the probe gets in an error state """
        logger.printmsg("debug", "reInitProbeClicked")
        # set init led to yellow
        self.setLEDyellow(self.probeStatusLED)
        self.reInitProbe.setText("Initializing ...")
        self.reInitProbe.repaint()  # Need this to show change immediately
        self.app.processEvents()
        status = self.client.initProbe()  # Initialize probe
        if status is True:  # reInit succeeded
            self.setLEDgreen(self.probeStatusLED)
            self.reInitProbe.setText("(Re)init Probe")
        else:  # reInit failed
            self.setLEDred(self.probeStatusLED)
            self.reInitProbe.setText("Init Failed - (Re)init Probe")

    def shutdownProbeClicked(self):
        logger.printmsg("debug", "shutdownProbe/quit clicked")
        self.client.close()
        logger.printmsg("debug", "Safe exit")
        self.app.exit(0)

    def waitForRadiometerWindow(self, isVisible=True):
        # Pauses program execution until ok pressed
        progress = QDialog()
        progress.setModal(False)
        if isVisible:
            progress.show()
            logger.printmsg("debug", "Show waitForRadiometerWindow")
        else:
            progress.hide()
            logger.printmsg("debug", "hide waitForRadiometerWindow")

        return False

    def scanStatusClicked(self):
        """ Start/Stop probe from scanning """
        logger.printmsg("debug", "scanStatusClicked")
        # Read current text to find out if we are cycling or not
        label = self.scanStatusButton.text()
        # set status led to yellow
        self.setLEDyellow(self.scanStatusLED)
        self.scanStatusButton.setText("...")
        self.scanStatusButton.repaint()  # Need this to show change immediately
        self.app.processEvents()
        if label == "Start Scanning":
            self.setLEDgreen(self.scanStatusLED)
            self.scanStatusButton.setText("Stop Scanning")
            self.client.cycle(self.app)
        if label == "Stop Scanning":
            self.setLEDred(self.scanStatusLED)
            self.scanStatusButton.setText("Start Scanning")
            self.client.stopCycle()

    def setLEDred(self, led):
        ICON_RED_LED = QtGui.QPixmap(QSize(30, 30))
        ICON_RED_LED.fill(QtGui.QColor("red"))
        led.setPixmap(ICON_RED_LED)

    def setLEDyellow(self, led):
        ICON_YELLOW_LED = QtGui.QPixmap(QSize(30, 30))
        ICON_YELLOW_LED.fill(QtGui.QColor("yellow"))
        led.setPixmap(ICON_YELLOW_LED)

    def setLEDgreen(self, led):
        ICON_GREEN_LED = QtGui.QPixmap(QSize(30, 30))
        ICON_GREEN_LED.fill(QtGui.QColor("green"))
        led.setPixmap(ICON_GREEN_LED)

    def setFlightNumber(self):
        # Dialog for setting flight number
        self.flightNumber.clear()
        self.flightNumber.setText("Target")

    def atTarget(self):
        # Update GUI
        # Note that having the clear here masks the 'target, target'
        # potential long scan indicator
        self.elAngleBox.clear()
        self.elAngleBox.setText("Target")

    def updateAngle(self, angle):
        self.elAngleBox.clear()
        self.elAngleBox.setText(angle)

    def updateGUIEndOfLoop(self, elapsedTime,
                           totalCycles, cyclesSinceLastStop):
        self.loopTimerBox.clear()
        self.loopTimerBox.setText("{:0.2f}".format(elapsedTime))
        self.totalNumFramesBox.clear()
        self.totalNumFramesBox.setText(totalCycles)
        self.numFramesSinceLastResetBox.clear()
        self.numFramesSinceLastResetBox.setText(cyclesSinceLastStop)
